### ISSUE TITLE
Migrate to JuliaGPU?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUSOLVER.jl#3]
I didn't know this existed until it was mentioned in the thread. I think having it in JuliaGPU would make it easier to find.I would think it would be a great asset to have in JuliaGPU! (I'm not a member of that org though)

**Comment by kshyatt** [comment]
Same, the reason I didn't migrate it is, as you can see, it's pretty barebones. I wanted to tag a new version AND do the migration and wasn't sure which order would be best.

**Comment by ChrisRackauckas** [comment]
Obviously it's not my choice, but I think it's developed enough to make it more visible so others can find it and submit PRs. I think mapping a more descriptive API then the "direct CUSOLVER function names" (a la [the discourse post](https://discourse.julialang.org/t/unified-interface-for-linear-solving/699/1)) would be all that's needed for this to be looking like a very complete library (and documentation of course!)

**Comment by tkelman** [comment]
And a package description more informative than "No description, website, or topics provided."

**Comment by kshyatt** [comment]
Sorry I've been neglecting this; if anyone would like to submit a PR for a better README I'd be very grateful. Otherwise I can try to knock something together soon.

**Comment by kshyatt** [comment]
Done. The README still needs improving but that can be a separate issue if you want to open it or a PR <3.
